[project]
name = "TradeSecureIOT"
authors = ["Gbolahan Akande"]
description = ""
telemetry = true
requirements = []
[contracts.escrow-contract]
path = "contracts/escrow-contract.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
